### ISSUE TITLE
Add a setup.py

### ISSUE THREAD

**Issue by mrueg** [pyupio/safety-db#1666]
As a user, I might want to have that datebase locally, is it possible to add a setup.py for that?

**Comment by jayfk** [comment]
So you can `pip install` it? Wouldn't it be easier to just clone the repo locally?

**Comment by mrueg** [comment]
Basically I'd want my package manager to take care of it and be able to use the tool in offline scenarios where a network connection might not be available

**Comment by jayfk** [comment]
That makes sense. Since you are in the gentoo org, you are probably talking about `portage`, right?

Is a simple `setup.py` enough, or has the package to be published on PyPI?

**Comment by mrueg** [comment]
Simple setup.py should be enough, safety is already packaged as https://packages.gentoo.org/packages/dev-python/safety

**Comment by jayfk** [comment]
Thanks!

Adding a `setup.py` here is a bit more complicated than I expected, because there is no real python package to be installed AND there's no easy way to create one on the fly.

Ideally I'd want to create a package on the fly that can be imported like this:

```
from safety_db import INSECURE_FULL, INSECURE
```

This would make it super easy to add an `--offline` option to `safety` that just tries to import the package and uses the data if it is installed.

**Comment by barseghyanartur** [comment]
@mrueg, @jayfk:

I have submitted a pull request solving the issue.

**Comment by jayfk** [comment]
Now available on PyPi: https://pypi.python.org/pypi/safety-db

Thanks again @barseghyanartur.
