### ISSUE TITLE
Please blacklist package ssh-decorator because of the backdoor it contains

### ISSUE THREAD

**Issue by Lucas-C** [pyupio/safety-db#2267]
Source: https://www.reddit.com/r/Python/comments/8hvzja/backdoor_in_sshdecorator_package/

**Comment by BobRawr101** [comment]
+1

**Comment by rafaelpivato** [comment]
@harlekeyn can you check this, please? It doesn't looks like we have a CVE for a case like this mainly because the package is a malicious package.

Honestly, I am not sure how we handle malicious packages as this tool main proposal is to check for published vulnerabilities and outdated software. Even with that in mind, this is a valid concern.

**Comment by harlekeyn** [comment]
Thank you @Lucas-C, for bringing this to our attention.
It has been added to our database.
