### ISSUE TITLE
The content of the data is sometimes confusing, especially which versions are affected

### ISSUE THREAD

**Issue by rustybrooks** [pyupio/safety-db#2284]
Consider the section below.  Is this the same as just saying "<2.3.1" since that essentially pre-empts all the other ones?

`ansible: [
"<1.2.3",
"<1.5.4",
"<1.5.5",
"<1.6.4",
"<1.6.6",
"<1.6.7",
"<1.7",
"<1.7.1",
"<1.8.3",
"<1.9.2",
"<1.9.6",
"<2.0.2",
"<2.2.1",
"<2.3.1"
],`

**Comment by 153957** [comment]
If a fix is backported to an earlier version it might make sense to show it like this, but only if it is known that a backported fix exists.

**Comment by rafaelpivato** [comment]
That is a known possible situation for the short DB version. It is the result of processing different reports on the full version. That happens when you have more than one report for the same package. Maybe we could "combine" them, but I am not sure that is required for a short list with just a few items on it.
