### ISSUE TITLE
Kombu, sendgrid: false positives, shouldn't safety mark sources as vulnerable?

### ISSUE THREAD

**Issue by m-aciek** [pyupio/safety-db#2347]
With the December update there are two vulnerabilities added that affect my project.
* first one is sendgrid vulnerability which comes from `starkbank-ecdsa`,
* second one – for Kombu – is connected with this commit https://github.com/celery/kombu/commit/f3b04558fa0df4ecc383c93e0b3b300d95e17c47, presumably it is about urllib3.

Shouldn't safety DB mark the source of vulnerabilities instead of libraries that use vulnerable packages as dependencies? This should help to maintain quality and potentially would save some false positives along the way.

**Comment by sparrowt** [comment]
> Shouldn't safety DB mark the source of vulnerabilities instead of libraries that use vulnerable packages as dependencies? This should help to maintain quality and potentially would save some false positives along the way.

Yes it seems strange to issue new entities like PVE-2021-42497 for `kombu` (and the knock-on PVE-2021-42498 for `celery`) when it would be better to just detect a vulnerable urllib3 version.

Especially given the spec `<5.2.1` is wrong because only Kombu `>=5.0` actually has a requirement for urllib3 at all (c.f. [this](https://github.com/celery/kombu/blob/4.6.9/requirements/extras/sqs.txt) vs [this](https://github.com/celery/kombu/blob/v5.2.2/requirements/extras/sqs.txt)), so this falsely causes Kombu 4.x to be flagged as vulnerable - flagging urllib3 instead would avoid this issue.

**Comment by SCH227** [comment]
The spec have been corrected. 
About the 'marking sources' issue:
We encourage performing scans on local environments because it allows a better fingerprinting of the packages' composition of a project. And in that case, you are right. It would be better to check directly for urllib3.
However, it could be the case of someone checking for vulnerabilities through a requirements.txt file.
In practice, requirements.txt files don't always list all the dependencies and sub-dependencies of a project. For that reason, to be on the security side, we mark the transitive vulnerabilities also for the parents packages.
Thank you for informing us!

**Comment by sparrowt** [comment]
Thanks for fixing the specs (I guess this won't be visible publicly til 1st Feb?) and for explaining your reasoning.
