### ISSUE TITLE
47833: You report that click is vulnerable, but the authors dont know about it? 

### ISSUE THREAD

**Issue by leberknecht** [pyupio/safety-db#2354]
Ahoi!

saftey started report that `click < 8.0.0.` is vulnerable, but the authors are not aware of this (see https://github.com/pallets/click/issues/2242 ). What is this about? If you get to know about vulnerabilities, dont you ping the vendors?

**Comment by SCH227** [comment]
@leberknecht our advisory points to the following issue in click's repo, which was fixed in version 8.0.0: 

>  Use of deprecated & insecure tempfile.mktemp()

https://github.com/pallets/click/issues/1752

The [Python documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp) is a good resource to read why it may be dangerous. 
You can also check the advisory for this [CVE](https://github.com/advisories/GHSA-wc4g-r73w-x8mm) recently reported for Tensorflow, which is a similar issue.
